### ISSUE TITLE
Use consistent formatting for special names

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-documentation#10]
e.g. _Lizmap-Web-Client_ is sometimes plain text, sometimes italic (I suggest always italic); media and other directories should be more differentiated from normal text; I suggest `media`.

**Comment by rldhont** [comment]
Agree with this proposition.

What do you thin about it @mdouchin ?

**Comment by rldhont** [comment]
Do we close this issue ?

**Comment by pcav** [comment]
I did not check the sources thoroughly. I'm unsure we have cleaned up all.

**Comment by Gustry** [comment]
This is and still a work in progress when I'm reviewing documentation.

better to update the `contributing.md` with this rules
