### ISSUE TITLE
Write doc to use lizmap-docker-compose

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-documentation#105]
Make a simple doc to help newbies with https://github.com/3liz/lizmap-docker-compose

**Comment by Gustry** [comment]
* At the top of https://docs.lizmap.com/current/en/install/pre_requirements.html
* and https://docs.lizmap.com/current/en/install/windows.html
Maybe it's enough ? Let's maintain a single doc about the docker-compose stack, located in https://github.com/3liz/lizmap-docker-compose

Is this OK for closing ?
