### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-documentation#106]
```
make gettext && make html
sphinx-build -b gettext   source i18n/pot
Running Sphinx v1.7.9

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 124, in <module>
    lizmap_versions = json.load(file('lizmap_versions.json'))
NameError: name 'file' is not defined

make: *** [Makefile:160: gettext] Error 2

```

**Comment by laurentj** [comment]
This is because you are using python 3 instead of python 2.7. I'll fix the conf.py

**Comment by laurentj** [comment]
Thank you for your report :-)

Thank you also for your commits! However, for changes about lizmap_3_2, prefer to commit into the lizmap_3_2 branch instead of into master, because we cannot merge master into lizmap_3_2 (but we can merge lizmap_3_2 into master, it's because of the version change into conf.py).

**Comment by pcav** [comment]
Thanks for the fast fix! Confirmed, now it works. Got a series of warnings, but that's minor.

**Comment by pcav** [comment]
As for my changes, thanks for incorporating it. Should I do my next changes on `release_3_2` branch?

**Comment by laurentj** [comment]
Yes please, do your next changes into the `lizmap_3_2` branch (not `release_3_2`) :-)

**Comment by pcav** [comment]
thanks, done already for Makefile - I assume you'll take care of the merge, or should I do something?
Thanks again.

**Comment by laurentj** [comment]
I'll take care of the merge

**Comment by pcav** [comment]
Merci
