### ISSUE TITLE
Remove pointers?

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-documentation#11]
I believe that with the source in en, the pointers to chapters, e.g.:

.. _hide_layers:

are useless, and can be removed.

**Comment by rldhont** [comment]
Do .rst recognize titles as pointers ?

**Comment by pcav** [comment]
Yes, see e.g. http://www.faunalia.eu/it/jobs.html#universita-e-centri-di-ricerca

**Comment by rldhont** [comment]
Well done it

**Comment by rldhont** [comment]
Do we close this issue ?

**Comment by pcav** [comment]
I believe so

**Comment by rldhont** [comment]
Thanks for your contribution.
