### ISSUE TITLE
Windows 10 installation

### ISSUE THREAD

**Issue by caduguedess** [3liz/lizmap-documentation#113]
The tutorial available at https://docs.lizmap.com/current/en/install/windows.html seems outdated.
It refers to Apache VC11 when there is already Apache VC15
It refers to PHP 5.6.23 when there is already PHP 7.3.6
I'm stuck in the PHP step of tutorial, because the tutorial says to uncomment the lines:
extension=php_curl.dll
extension=php_fileinfo.dll
extension=php_gd2.dll
extension=php_mbstring.dll
extension=php_pdo_pgsql.dll
extension=php_pdo_sqlite.dll
extension=php_pgsql.dll
extension=php_sqlite3.dll
But none of these lines exists in the php.ini file, causing warnings when i run php -m command at cmd.

**Comment by Gustry** [comment]
We do not support installation on Windows : see https://docs.lizmap.com/current/en/install/windows.html
