### ISSUE TITLE
Add notes about QGIS Server version 3 support

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-documentation#114]
Add a notes for version 3.1, 3.2 and 3.3 about QGIS Server 3 support :

* For version 3.1 : QGIS Server 3 is unsupported
* For version 3.2 : QGIS Server 3 is partialy supported
* For version 3.3 : QGIS Server 3 is fully supported

**Comment by Gustry** [comment]
I think we should have a kind of table like showing current versions too at the beginning of the documentation.

Similar to
https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule

**Comment by Gustry** [comment]
Done 8e5017f
