### ISSUE TITLE
seeding script : level

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-documentation#116]
How can we know what are the useful values for ​​'TileMatrixMin' and 'TileMatrixMax' ?
When i run the script `/script.php lizmap~wmts:capabilities`, it always returns :
`For "layer" and "EPSG:3857" from TileMatrix 0 to 19` 
But I only use scales between 50000 and 1000 and I don't want to generate too much tiles.

**Comment by Gustry** [comment]
I will try to improve the documentation a little bit here
