### ISSUE TITLE
Remove old version of QGIS

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-documentation#120]
I think, from time to time, we should remove from master some quotes with some old version of QGIS.

> Vous pouvez utiliser des relations « plusieurs-à-plusieurs » (N:M) dans QGIS depuis la version 2.14 mais à ce jour Lizmap ne les utilisent pas automatiquement. 

https://docs.lizmap.com/current/fr/publish/advanced_lizmap_config.html#activate-the-attribute-table-tool-for-a-vector-layer

**Comment by pcav** [comment]
+1

**Comment by Gustry** [comment]
Lizmap web client is still compatible QGIS 2 etc, so I decided to keep these references. 

So as to keep a reference, I'm changing to some RST substitutions `|qgis_2|`, `|qgis_3|` ...

But I'm removing Lizmap 3.1, 3.2, because the documentation is versionned.
