### ISSUE TITLE
Reorganize the documentation

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-documentation#126]
URL : 
* master branch https://docsbeta.lizmap.com/next/en/publish/index.html
* 3.3 branch https://docs.lizmap.com/current/en/publish/index.html

## Now

Currently, the documentation in the "Publisher guide" has 4 sections:
* Prepare a QGIS project  
* Setup your project for lizmap
* Publish the map by FTP
* Advanced configuration
  * A lot of subsection here !

Each of these items have their own URL. (4 urls right now)

## Problems

Problems are:
* The Advanced configuration gets bigger and bigger
* The advanced configuration is *mixing* some Lizmap Panels configuration, some QGIS core configuration, some optimizations (printing of base layer, DB, etc ...)
* These subsection in the advanced configuration are not in a good order. Some lizmap panels are in the wrong order compare to the QGIS plugin and some lizmap panels description are interrupted by another topic when we read from to bottom.
* Only 4 pages (4 urls)

## Idea

I would like to have something more like this IMHO:
* Quickstart guide (one URL for each items below, like today)
  * Prepare a QGIS project
  * Setup your project for lizmap
  * Publish the map by FTP
  * Basic Lizmap web client configuration to display the project
* Lizmap plugin panels (tools?) (documentation for each Lizmap plugin panels, in the correct order of the QGIS plugin). One URL for each item.
  * Options
  * Layers (add links into other section which are more described, such "how to configure popups")
  * Localize
  * Attribute table
  * Edition
  * Maptip
  * Login filtering
  * Dataviz
  * Time manager
  * Atlas
  * Form filtering
* Other configuration (To take some sections which are already in the existing documentation under the advanced section). Some of these topics are QGIS configuration only (such as map themes). Maybe a single page for these items below?
  * Create an overview map
  * Changing the default image of a project
  * Spatial searching
  * Media in lizmap
  * how to configure popups (referenced from the panel for instance)
  * Create simple themes
  * Adding your own javascript
  * Printing configuration
  * Optimize Lizmap
  * The new map themes in LWC 3.4
  * Etc ...

It would be nice to add one more level in pages generation (more URL). For the section Lizmap plugin panels, it would be nice I think to have one page for each panel (so we don't have a long page to scroll). is-that possible ?

Any idea how to improve the state of the documentation?

**Comment by pcav** [comment]
Agreed, a cleanup is very much welcome. Your proposal looks good to me. Thanks @Gustry

**Comment by laurentj** [comment]
The "Other configuration" chapter should be renamed "Customization" or something like that, isn't it? If some sections are not related to customization, then we should split the chapter into two chapters.

**Comment by Gustry** [comment]
I still have some work on this ticket. I merge the first PR. I will come back soon.

**Comment by Gustry** [comment]
Done, the master branch is now way better.

**Comment by pcav** [comment]
Nice improvement, thanks!

**Comment by Gustry** [comment]
@pcav It's not finished. If you want a preview, you can see the master branch with this link : https://docs.lizmap.com/next/en/

It's mainly the publisher guide which had a big refactoring.

**Comment by pcav** [comment]
Yes, I cloned and compiled it.
