### ISSUE TITLE
Add action buttons in the popup

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-documentation#133]
![imagem](https://user-images.githubusercontent.com/10053874/72422005-7dd67a80-3779-11ea-99ba-303b9f883009.png)

`lizmap_pg_api_example.png` is missing...

thanks

**Comment by Gustry** [comment]
Please provide some context next time : where is this picture located ? Any URL, page ?

The string `lizmap_pg_api_example` is not found on GitHub anymore https://github.com/search?q=org%3A3liz%20lizmap_pg_api_example&type=code
