### ISSUE TITLE
Map builder is missing

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-documentation#135]
Documentation about map builder is missing in the documentation.

Or should we redirect users to the Github repository for Lizmap modules?

**Comment by nboisteault** [comment]
Maybe we could add a page quickly presenting lizmap modules.

**Comment by Gustry** [comment]
Yes, it's ticket https://github.com/3liz/lizmap-documentation/issues/136 ;-) and https://docs.lizmap.com/next/en/introduction.html#additional-lizmap-modules
Single page quickly presenting lizmap modules or proper help for some modules?

**Comment by nboisteault** [comment]
I think it is enough if README.md for some modules (mapbuilder for instance :) ) is improved.

**Comment by Gustry** [comment]
Ok, so I'm closing.
