### ISSUE TITLE
Improve Lizmap introduction and the schema

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-documentation#137]
Found on a blog talking about Lizmap :)

![Capture d’écran de 2020-01-22 12-04-47](https://user-images.githubusercontent.com/1609292/72889294-a2999780-3d0f-11ea-85d4-cfa95aad08fb.png)

**Comment by nboisteault** [comment]
Which blog ?

**Comment by Gustry** [comment]
http://adrien.caillot.free.fr/?p=25294

**Comment by nboisteault** [comment]
Image is no more visible as we changed it for jpg and blog author "hotlinked" the old one.

**Comment by Gustry** [comment]
I saw, there is the SVG inthe folder. I will try to improve it, at least to mention Lizmap.

**Comment by Gustry** [comment]
Done, quickly.  It can still be improved. At least, it has the QGIS 3 logo, Lizmap is mentioned, a little bit refreshed
https://github.com/3liz/lizmap-documentation/commit/8f7d777dcc85abcec5ebd3a10f5303298e32f408
