### ISSUE TITLE
Document the "Service non disponible" / error 500

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-documentation#151]
I think "Service non disponible" is the most common issue with Lizmap AND/OR QGIS Server.

We should have a page explaining possible problems leading to this error message, either related to QGIS Server or to Lizmap Config.

* Check QGIS Server logs to get the invalid layers and to be sure that every layers defined in the project are avaible for the server.

Please add more tips.

**Comment by dmarteau** [comment]
Lizmap should relay the qgis error if available or return a more appropriate error (502 or 504).

**Comment by pcav** [comment]
In my experiance these are usually due to permissions, and are solved by the `set_rights` script.

**Comment by Gustry** [comment]
It's mainly due to the behaviour of QGIS Server when there is an invalid layer. The whole project is invalid. We need to add
https://github.com/qgis/QGIS-Documentation/issues/5277 which in the lastest QGIS 3.10 bug release

**Comment by Gustry** [comment]
This has been improved in LWC core about managing HTTP error code from QGIS server and also checking QGIS server is working with the Lizmap server plugin.
