### ISSUE TITLE
Editing on Spatialite

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-documentation#164]
Is this still true?
https://github.com/3liz/lizmap-documentation/blob/master/source/install/linux.rst#spatialite
I assume editing can only be done on pg.

**Comment by Gustry** [comment]
According to QGIS plugin code, postgres and spatialite are enabled. I haven't tested.

**Comment by pcav** [comment]
I have people who tested it without success. Is Spatialite handling concurrence?

**Comment by Gustry** [comment]
Spatialite has been removed from a long time in the plugin, and it has been definitely removed in LWC core.
