### ISSUE TITLE
Documentation for windows - qgis-server-plugins

### ISSUE THREAD

**Issue by sergiuspinheiro** [3liz/lizmap-documentation#170]
It would be possible to document the windows installation with the same information as the linux installation
https://docs.lizmap.com/current/pt/install/linux.html#qgis-server-plugins

**Comment by Gustry** [comment]
Done in 584b24121eadf9899ff35a8a990aa66956bbbae1

It's not dependent of the OS : Linux/Windows etc. It's only requirements before installing Lizmap.
