### ISSUE TITLE
add document pages for Japanese language

### ISSUE THREAD

**Issue by JinIgarashi** [3liz/lizmap-documentation#178]
We are now translating Lizmap documentation to Japanese language in transfex.

We already completed translations in some section, could you add ja pages in your site (https://docs.lizmap.com)? So it will help us translate by confirming how the translations appear in the site.

**Comment by Gustry** [comment]
It's done, you can see the preview on https://docs.lizmap.com/next/ja/ for files related to LWC 3.5

For LWC 3.4 : https://docs.lizmap.com/next/ja/

I didn't enabled it for lower version of LWC, do not translate them on transifex I think. (3.1, 3.2, 3.3)

Feel free to reopen a new tickt if necessary.

**Comment by JinIgarashi** [comment]
@Gustry Thank you! I can see now the ja pages, however there is no Japanese text strings appear in the site?? We completed `master-indexpot_1` and `master-introductionpot` now, but it's still in English.

https://docs.lizmap.com/next/ja/introduction.html

How often do you frequently update the documentation by CI because we are on-going translation? it's better to update frequently and automatically.

**Comment by Gustry** [comment]
Indeed, I forgot to update the CI. Fixed in 1804fea1f3abdaee0625851be68d04b18f1c460a

https://docs.lizmap.com/current/ja/introduction.html
https://docs.lizmap.com/next/ja/introduction.html

Maybe make a hard refresh in browser if needed.

If need, you can translate screenshot and make pull requests.

**Comment by JinIgarashi** [comment]
@Gustry Thanks a lot! Now I can see my translations! Will the CI update everyday?

**Comment by Gustry** [comment]
The CI updates our internal private website everyday. But indeed, on the production public website, it's currently on a manual trigger. Let us think what we can improve.

We will contact you soon by mail.
