### ISSUE TITLE
Wrong syntax in apache config on the windows.rst page

### ISSUE THREAD

**Issue by blaisegeo** [3liz/lizmap-documentation#182]
Somebody had an issue when installing lizmap on windows  following this doc yesterday, check this georezo thread:
https://georezo.net/forum/viewtopic.php?id=124670

The Apache documentation states that comments in config files can NOT start in the middle of a line, only at the beginning.
https://httpd.apache.org/docs/2.4/en/configuring.html
` Comments may **not** be included on the same line as a configuration directive. `

Thus, in the windows.rst page of the lizmap doc, on the Apache 2.4.41 Server Configuration section, the examples to set a virtual host raise apache errors because some lines have comments starting on the same lines  as the directives. For example line 2:

Include conf/extra/php73.conf #include the diretory conf file for php73 configuration

which raise the following apache error:

httpd.exe: Syntax error on line 511 of C:/webserver/Apache24/conf/httpd.conf: Syntax error on line 33 of C:/webserver/Apache24/conf/extra/httpd-vhosts.conf: Include takes one argument, Name(s) of the config file(s) to be included; fails if the wildcard does not match at least one file

I can see this error 3 times on the first virtual host config example, and twice on the second virtual host config example.

Best regards

**Comment by Gustry** [comment]
We do not support installation on Windows : see https://docs.lizmap.com/current/en/install/windows.html
