### ISSUE TITLE
Actions - Add the new features and configuration modification for LWC 3.7

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-documentation#227]
See the new features https://github.com/3liz/lizmap-web-client/pull/3343

**Comment by Gustry** [comment]
Linked to https://github.com/3liz/lizmap-plugin/issues/515 for the plugin

For the new format : https://github.com/3liz/lizmap-web-client/pull/3339

**Comment by Gustry** [comment]
* [ ] Move the tab in the "lizmap plugin" and backport

**Comment by Gustry** [comment]
The documentation has been patched quickly to link the PR : 446db57c8daf299a95d449ddff893ec25045cdef

**Comment by Gustry** [comment]
The documentation has moved from "configurations" to "lizmap_plugin" : 33226543b1deb14bb5131aad97d08d7408734958 and https://github.com/3liz/lizmap-plugin/commit/9996baacf474fb782e14909204776eb5ddafd5a8

**Comment by Gustry** [comment]
Nicely hidden this one : https://github.com/3liz/lizmap-web-client/commit/4ffb2a31acaec91af1b0ddf7f9f4141158b579a1 :)
