### ISSUE TITLE
media folder "theme" typo + confusing theme guide

### ISSUE THREAD

**Issue by erw-1** [3liz/lizmap-documentation#263]
In https://docs.lizmap.com/3.8/en/publish/configuration/media.html, "Replacing the default theme, **media/theme**" the folder location should be "**media/themes**" here.

To make the process less confusing, and because there is no concrete theme example in this page, I also added this in the "[Use a single media folder for many Lizmap folders](https://docs.lizmap.com/3.8/en/publish/configuration/media.html#use-a-single-media-folder-for-many-lizmap-folders)"'s example tree.

```bash
    ├── media
    │   └── js
    │   |    └── default
    │   |       ├── another_script.js
    │   |       └── one_script.js
    │   └── themes
    │   |    └── default
    │   |       └── css
    │   |          ├── main.css
    │   |          └── map.css 
    │   └── photo_1.jpg
    ...
   ```

**Comment by erw-1** [comment]
https://github.com/3liz/lizmap-documentation/pull/264

**Comment by Gustry** [comment]
Thanks for the ticket.

For this kind of ticket, you could make straight the PR for next time, as it seems you already got it ;-)

**Comment by erw-1** [comment]
Alright! I appreciate the tip, still new to contributing

**Comment by Gustry** [comment]
This issue is quite straight forward to fix, so yo can make the PR straight, if you want to earn some time.

Thanks for your contributions on LWC ! 😉
