### ISSUE TITLE
Error when compiling locally

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-documentation#46]
If I clone the repo and compile it locally, I get an error:

This is an documentation error, please report back to QGIS devs.

Unclear how to clean up this. Nothing serious, but better to iron it out.

**Comment by 3liz** [comment]
Hi @paolo,

I use these commands to build lizmap documentation:
```
sphinx-intl update -d i18n
sphinx-intl build -d i18n
sphinx-build -b html source/ build/html/en/
sphinx-build -b html -D language='fr' source/ build/html/fr/
```

**Comment by paolo** [comment]
Hi, you may wanna re tag the right Paolo :)

**Comment by pcav** [comment]
I use simply ``make html``, but even when doing the same as you, I get the error.

**Comment by pcav** [comment]
My mistake - /en/ or other language should be added to the address.
Sorry for the noise.
