### ISSUE TITLE
Publishing primary key for filtering data

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-documentation#55]
The lizmap web client issue 304 https://github.com/3liz/lizmap-web-client/issues/304 is linked to this issue.

**Comment by luckgentilpiron** [comment]
If you want to filter data with the filter tool

![capture d ecran 2016-05-09 a 12 03 22](https://cloud.githubusercontent.com/assets/19183407/15109955/63c6160c-15de-11e6-8223-f853d290195c.png)

You must publish your primary key in WFS in your QGIS Project (Properties > Fields)

![capture d ecran 2016-05-09 a 12 01 13](https://cloud.githubusercontent.com/assets/19183407/15110026/d25d7f42-15de-11e6-8158-d5d1122a7f48.png)

**Comment by Gustry** [comment]
I hope I understood the issue : 1ea25e4310ca2f565ccb8d93b6d30f22e8b2193a
