### ISSUE TITLE
Add deprecating Geolocation on Insecure Origins

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-documentation#57]
As chromium said:
> getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature, 
> you should consider switching your application to a secure origin, such as HTTPS. See
> https://goo.gl/rStTGz for more details.

So we have to add these information in the documentation to help people.

**Comment by pcav** [comment]
Done: https://github.com/3liz/lizmap-documentation/pull/58

**Comment by rldhont** [comment]
Fixed in #58
