### ISSUE TITLE
[Windows OS][Instalation] Add configuration in php5-.x.x.conf to activate more output formats Lizmap Web Client

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-documentation#61]
To activate the server plugin **qgis-wfsOutputExtension** and activate the rest of output formats in lizmap web client we need to add this lines in **php-5.x.x.conf** in the Apache folder **Apache24\conf\extra**:

```
FcgidIOTimeout 120
        FcgidInitialEnv LC_ALL "en_US.UTF-8"
        FcgidInitialEnv PYTHONIOENCODING UTF-8
        FcgidInitialEnv LANG "en_US.UTF-8"
        FcgidInitialEnv QGIS_DEBUG 1
        FcgidInitialEnv QGIS_SERVER_LOG_FILE "C:\\webserver\Apache24\logs\\qgis_server.log"
        FcgidInitialEnv QGIS_SERVER_LOG_LEVEL 0
        FcgidInitialEnv QGIS_PLUGINPATH "C:\OSGeo4W64\apps\qgis-ltr\python\plugins"
```

And put the folder of plugin qgis-wfsOutputExtension in the **C:\OSGeo4W64\apps\qgis-ltr\python\plugins** (in this case, i don't test yet another directory for pluginpath but i think that will work)

Tested and working with:
- Windows Server 2008 R2
- QGIS Server 2.14.5 LTR 64bits
- LizMap Web Client 3.0.1
- Apache 2.4.20
- PHP 5.6.23

Regards
João

**Comment by mdouchin** [comment]
Hi, could you create a PR for this ?
Thanks in advance

**Comment by jonnyforestGIS** [comment]
No problem :+1:

**Comment by jonnyforestGIS** [comment]
@mdouchin you can close this i just add this in documentation. 
Regards, João

**Comment by rldhont** [comment]
Done by merging
