### ISSUE TITLE
[Windows OS]Add steps for update new versions of Lizmap web client

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-documentation#67]
Hi don't test yet in windows.  After the tests i will add the steps.

Regards
João

**Comment by Gustry** [comment]
Do you still have some steps to add?

**Comment by jonnyforestGIS** [comment]
This can be close I add the recent updates.

**Comment by Gustry** [comment]
Ok, thanks. I'm trying to clean old tickets step by  step
