### ISSUE TITLE
Use proper sphinx classes

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-documentation#7]
e.g.
.. warning:: 
instead of
.. note:: ATTENTION
,
.. seealso::
instead of
.. note:: Voir aussi

etc.

**Comment by rldhont** [comment]
Your right, you can do it.

**Comment by rldhont** [comment]
Do we close this issue ?

**Comment by pcav** [comment]
I think so. Better grepping through the repo before closing, however.

**Comment by Gustry** [comment]
Should we close?

**Comment by pcav** [comment]
It should be OK, but a quick grep to check it is currently consistent will not hurt.

**Comment by Gustry** [comment]
Already did sorry
