### ISSUE TITLE
Localize the figures

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-documentation#72]
Figures can be localized with standard sphinx approach. In the process, images can be refreshed.
I'm available to do it.
Can I start? Should I use the Montpellier demo project?

**Comment by rldhont** [comment]
Of course!
Thanks @pcav

**Comment by pcav** [comment]
Could you please recall me how to show the interface in a lang different from that of the browser?
Merci.

**Comment by rldhont** [comment]
You can use `lang` parameter with the value of a langage available in lizmap: it_IT, pt_PT, fr_FR, en_US, es_ES, gl_ES, etc...

**Comment by pcav** [comment]
http://wwwserver.ext/webgis/admin.php/jacl2db_admin/groups/rights&lang=it_IT
throws a 500 error

**Comment by rldhont** [comment]
@pcav like this: http://wwwserver.ext/webgis/admin.php/jacl2db_admin/groups/rights?lang=it_IT

**Comment by pcav** [comment]
Work started

**Comment by pcav** [comment]
First PR: https://github.com/3liz/lizmap-documentation/pull/73

**Comment by Gustry** [comment]
Yesterday @nboisteault made a PR about translation of figures.

You have the readme here https://github.com/3liz/lizmap-documentation/blob/master/source/images/README.md

Can we close this issue?

**Comment by Gustry** [comment]
This ticket will be always work in progress because we keep adding screenshots in English from time to time. Please read the link above how to translate pictures.
