### ISSUE TITLE
Use consistent style for menu entries, etc.

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-documentation#9]
I think mannu entries should always have the same style, e.g. **menu**, _menu_, or `menu`.
Or: :menuselection:`Menu --> Submenu`
See the main QGIS manual for consistency, e.g. QGIS-Documentation/source/docs/user_manual/preamble/conventions.rst

**Comment by rldhont** [comment]
We have to use the same convention as QGIS https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/user_manual/preamble/conventions.rst

I also found this file: https://github.com/qgis/QGIS-Documentation/tree/master/source/docs/documentation_guidelines

**Comment by rldhont** [comment]
Do we close this issue ?

**Comment by pcav** [comment]
I did not check the sources thoroughly. I'm unsure we have cleaned up all.

**Comment by Gustry** [comment]
This a work in progress. We are doing it step by step.
A lot has been done in the meantime and a lot of translations are lost in the current `master` branch.
