### ISSUE TITLE
/source/user/user_guide.rst is a too heavy page

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-documentation#97]
This page is very heavy so difficult to download for slow connections.
I've tested it on WebPageTest : http://www.webpagetest.org/result/180629_N3_48c3dc584c74f7093df0d25a1f484c1a/1/details/#waterfall_view_step1

It weights 20 Mo because of numerous images and also compression should be enabled for some ressources : http://www.webpagetest.org/performance_optimization.php?test=180629_N3_48c3dc584c74f7093df0d25a1f484c1a&run=1#compress_text

**Comment by rldhont** [comment]
feel free to split it!

**Comment by Gustry** [comment]
Done ! :)

**Comment by rldhont** [comment]
thanks
